package orpg.shared;

public enum ErrorMessage {

	ACCOUNT_ALREADY_EXISTS, 
	ACCOUNT_NAME_HAS_INVALID_CHARACTERS,
	GENERIC_ACCOUNT_CREATION_ERROR, 
	LOGIN_INVALID_CREDENTIALS,
	GENERIC_LOGIN_ERROR

}
